version: '3.8'

services:
  springboot:
    container_name: springboot
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - springboot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
